name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout repository

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run tests and container
      run: |
        docker run -d -p 888:88 docker-tests
        sleep 5
        curl -sSf http://localhost:888 || exit 1
        echo "My test task is completed!"

    - name: Stop and remove the container
      run: docker stop $(docker ps -q --filter ancestor=docker-tests)
