name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t mydockerimage:latest .

    - name: Run Docker container
      run: |
        docker run -d -p 888:88 mydockerimage:latest
        echo "docker is runned!"

    - name: Test server
      run: |
        echo "start tests!"
        sleep 15
        echo "success delay!"
        curl http://localhost:888
        echo "My test task is completed!"

    - name: Stop and remove the container
      run: docker stop $(docker ps -q --filter ancestor=mydockerimage)
